// ------------------ Dummy Products ------------------
const allProducts = [
  {
    id: 1,
    name: "Onions",
    description: "High quality onions",
    category_id: "Vegetables",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=12579&format=png", // Onion icon
    ],
    variants: [
      {
        id: 1,
        variant_name: "2 ml",
        regular_price: 685,
        discounted_price: 642,
        stock_quantity: 9,
        unit: "unit",
        sku: "VEG-1-1",
        status: "low stock",
      },
    ],
    createdAt: "2025-12-08T03:16:32.015922",
    updatedAt: "2025-12-10T09:16:31.015922",
  },
  {
    id: 2,
    name: "Premium Rice",
    description: "High quality premium rice",
    category_id: "Beverages",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=23330&format=png", // Cereal/Grains icon
      "https://img.icons8.com/?size=80&id=59822&format=png", // Sack icon
    ],
    variants: [
      {
        id: 1,
        variant_name: "5 g",
        regular_price: 598,
        discounted_price: 563,
        stock_quantity: 27,
        unit: "pack",
        sku: "BEV-2-1",
        status: "available",
      },
      {
        id: 2,
        variant_name: "4 ml",
        regular_price: 487,
        discounted_price: 475,
        stock_quantity: 38,
        unit: "ml",
        sku: "BEV-2-2",
        status: "available",
      },
    ],
    createdAt: "2025-11-02T10:48:21.015922",
    updatedAt: "2025-11-11T15:02:34.015922",
  },
  {
    id: 3,
    name: "Chicken Breast",
    description: "High quality chicken breast",
    category_id: "Dairy & Eggs",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=23331&format=png", // Meat icon
    ],
    variants: [
      {
        id: 1,
        variant_name: "4 unit",
        regular_price: 165,
        discounted_price: 149,
        stock_quantity: 1,
        unit: "g",
        sku: "DAIRY-3-1",
        status: "low stock",
      },
      {
        id: 2,
        variant_name: "4 pack",
        regular_price: 204,
        discounted_price: 161,
        stock_quantity: 40,
        unit: "pack",
        sku: "DAIRY-3-2",
        status: "available",
      },
    ],
    createdAt: "2025-10-04T15:28:08.015922",
    updatedAt: "2025-10-25T07:10:19.015922",
  },
  {
    id: 4,
    name: "Tomatoes",
    description: "High quality tomatoes",
    category_id: "Rice Products",
    is_active: false,
    images: [
      "https://img.icons8.com/?size=80&id=12686&format=png", // Tomato icon
    ],
    variants: [
      {
        id: 1,
        variant_name: "4 L",
        regular_price: 318,
        discounted_price: 279,
        stock_quantity: 44,
        unit: "kg",
        sku: "RICE-4-1",
        status: "available",
      },
    ],
    createdAt: "2025-11-25T23:41:16.015922",
    updatedAt: "2025-12-10T07:09:30.015922",
  },
  {
    id: 5,
    name: "Basmati Rice",
    description: "High quality basmati rice",
    category_id: "Sweeteners",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=12579&format=png", // Cereal/Grains icon
    ],
    variants: [
      {
        id: 1,
        variant_name: "1 L",
        regular_price: 828,
        discounted_price: 820,
        stock_quantity: 33,
        unit: "unit",
        sku: "SUGAR-5-1",
        status: "available",
      },
    ],
    createdAt: "2025-10-29T01:19:07.015922",
    updatedAt: "2025-11-24T16:42:26.015922",
  },
  {
    id: 6,
    name: "Cooking Oil",
    description: "High quality cooking oil",
    category_id: "Beverages",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=59750&format=png", // Your confirmed working link (Bottle/Oil)
      "https://img.icons8.com/?size=80&id=12686&format=png",
    ],
    variants: [
      {
        id: 1,
        variant_name: "2 L",
        regular_price: 318,
        discounted_price: 270,
        stock_quantity: 3,
        unit: "L",
        sku: "BEV-6-1",
        status: "low stock",
      },
      {
        id: 2,
        variant_name: "5 pack",
        regular_price: 438,
        discounted_price: 406,
        stock_quantity: 49,
        unit: "L",
        sku: "BEV-6-2",
        status: "available",
      },
      {
        id: 3,
        variant_name: "2 ml",
        regular_price: 713,
        discounted_price: 695,
        stock_quantity: 33,
        unit: "unit",
        sku: "BEV-6-3",
        status: "available",
      },
    ],
    createdAt: "2025-10-04T07:52:58.015922",
    updatedAt: "2025-10-13T03:04:35.015922",
  },
  {
    id: 7,
    name: "Cooking Oil",
    description: "High quality cooking oil",
    category_id: "Rice Products",
    is_active: false,
    images: ["https://img.icons8.com/?size=80&id=59750&format=png"],
    variants: [
      {
        id: 1,
        variant_name: "5 pack",
        regular_price: 448,
        discounted_price: 419,
        stock_quantity: 22,
        unit: "kg",
        sku: "RICE-7-1",
        status: "available",
      },
    ],
    createdAt: "2025-10-18T09:21:39.015922",
    updatedAt: "2025-11-03T02:44:00.015922",
  },
  {
    id: 8,
    name: "Multigrain Flour",
    description: "High quality multigrain flour",
    category_id: "Beverages",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=23330&format=png",
      "https://img.icons8.com/?size=80&id=59822&format=png",
    ],
    variants: [
      {
        id: 1,
        variant_name: "4 g",
        regular_price: 709,
        discounted_price: 669,
        stock_quantity: 14,
        unit: "kg",
        sku: "BEV-8-1",
        status: "available",
      },
      {
        id: 2,
        variant_name: "3 pack",
        regular_price: 843,
        discounted_price: 805,
        stock_quantity: 19,
        unit: "kg",
        sku: "BEV-8-2",
        status: "available",
      },
    ],
    createdAt: "2025-09-18T08:22:11.015922",
    updatedAt: "2025-11-09T12:29:49.015922",
  },
  {
    id: 9,
    name: "Cooking Oil",
    description: "High quality cooking oil",
    category_id: "Flours & Grains",
    is_active: true,
    images: ["https://img.icons8.com/?size=80&id=59750&format=png"],
    variants: [
      {
        id: 1,
        variant_name: "4 kg",
        regular_price: 669,
        discounted_price: 633,
        stock_quantity: 34,
        unit: "ml",
        sku: "FLOUR-9-1",
        status: "available",
      },
    ],
    createdAt: "2025-10-15T09:17:20.015922",
    updatedAt: "2025-11-14T07:05:52.015922",
  },
  {
    id: 10,
    name: "Multigrain Flour",
    description: "High quality multigrain flour",
    category_id: "Oils & Fats",
    is_active: false,
    images: [
      "https://img.icons8.com/?size=80&id=59822&format=png",
      "https://img.icons8.com/?size=80&id=23330&format=png",
    ],
    variants: [
      {
        id: 1,
        variant_name: "5 ml",
        regular_price: 330,
        discounted_price: 308,
        stock_quantity: 5,
        unit: "L",
        sku: "OIL-10-1",
        status: "low stock",
      },
      {
        id: 2,
        variant_name: "2 pack",
        regular_price: 985,
        discounted_price: 961,
        stock_quantity: 32,
        unit: "ml",
        sku: "OIL-10-2",
        status: "available",
      },
      {
        id: 3,
        variant_name: "4 ml",
        regular_price: 542,
        discounted_price: 519,
        stock_quantity: 12,
        unit: "unit",
        sku: "OIL-10-3",
        status: "available",
      },
    ],
    createdAt: "2025-11-06T17:29:53.015922",
    updatedAt: "2025-11-07T17:02:33.015922",
  },
  {
    id: 11,
    name: "Eggs (Large)",
    description: "High quality eggs (large)",
    category_id: "Beverages",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=12579&format=png", // Eggs icon
      "https://img.icons8.com/?size=80&id=12686&format=png",
    ],
    variants: [
      {
        id: 1,
        variant_name: "5 L",
        regular_price: 325,
        discounted_price: 288,
        stock_quantity: 6,
        unit: "kg",
        sku: "BEV-11-1",
        status: "low stock",
      },
    ],
    createdAt: "2025-11-10T01:39:05.015922",
    updatedAt: "2025-11-25T21:29:10.015922",
  },
  {
    id: 12,
    name: "Black Coffee",
    description: "High quality black coffee",
    category_id: "Vegetables",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=59750&format=png", // Coffee cup icon (or similar)
      "https://img.icons8.com/?size=80&id=23331&format=png",
    ],
    variants: [
      {
        id: 1,
        variant_name: "4 L",
        regular_price: 782,
        discounted_price: 782,
        stock_quantity: 43,
        unit: "pack",
        sku: "VEG-12-1",
        status: "available",
      },
      {
        id: 2,
        variant_name: "3 kg",
        regular_price: 509,
        discounted_price: 485,
        stock_quantity: 36,
        unit: "unit",
        sku: "VEG-12-2",
        status: "available",
      },
    ],
    createdAt: "2025-11-30T16:00:33.015922",
    updatedAt: "2025-12-06T06:39:31.015922",
  },
  {
    id: 13,
    name: "Black Coffee",
    description: "High quality black coffee",
    category_id: "Rice Products",
    is_active: false,
    images: ["https://img.icons8.com/?size=80&id=59750&format=png"],
    variants: [
      {
        id: 1,
        variant_name: "1 ml",
        regular_price: 85,
        discounted_price: 44,
        stock_quantity: 14,
        unit: "kg",
        sku: "RICE-13-1",
        status: "available",
      },
    ],
    createdAt: "2025-09-14T14:19:56.015922",
    updatedAt: "2025-09-21T23:26:17.015922",
  },
  {
    id: 14,
    name: "Basmati Rice",
    description: "High quality basmati rice",
    category_id: "Vegetables",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=59822&format=png", // Sack icon
      "https://img.icons8.com/?size=80&id=23330&format=png",
    ],
    variants: [
      {
        id: 1,
        variant_name: "2 pack",
        regular_price: 670,
        discounted_price: 655,
        stock_quantity: 0,
        unit: "kg",
        sku: "VEG-14-1",
        status: "out of stock",
      },
    ],
    createdAt: "2025-09-28T07:16:03.015922",
    updatedAt: "2025-10-19T14:30:32.015922",
  },
  {
    id: 15,
    name: "Brown Sugar",
    description: "High quality brown sugar",
    category_id: "Beverages",
    is_active: true,
    images: [
      "https://img.icons8.com/?size=80&id=12686&format=png", // Sugar cube/Sweetener icon
    ],
    variants: [
      {
        id: 1,
        variant_name: "5 pack",
        regular_price: 691,
        discounted_price: 641,
        stock_quantity: 2,
        unit: "g",
        sku: "BEV-15-1",
        status: "low stock",
      },
      {
        id: 2,
        variant_name: "2 pack",
        regular_price: 71,
        discounted_price: 68,
        stock_quantity: 40,
        unit: "L",
        sku: "BEV-15-2",
        status: "available",
      },
    ],
    createdAt: "2025-11-13T18:44:19.015922",
    updatedAt: "2025-12-06T01:33:42.015922",
  },
];
export default allProducts;
