export const productVariants = [
  {
    id: "pv_001",
    product_id: "prod_rice_01",
    variant_name: "Ponni Rice – 5kg",
    regular_price: 750,
    discounted_price: 699,
    stock_quantity: 120,
    unit: "5 kg",
    sku: "RICE-PON-5KG",
    status: "active",
  },
  {
    id: "pv_002",
    product_id: "prod_rice_01",
    variant_name: "Ponni Rice – 10kg",
    regular_price: 1450,
    discounted_price: 1350,
    stock_quantity: 80,
    unit: "10 kg",
    sku: "RICE-PON-10KG",
    status: "active",
  },
  {
    id: "pv_003",
    product_id: "prod_mirchi_01",
    variant_name: "Guntur Red Chilli – 1kg",
    regular_price: 520,
    discounted_price: 499,
    stock_quantity: 0,
    unit: "1 kg",
    sku: "MIRCHI-GUN-1KG",
    status: "out_of_stock",
  },
  {
    id: "pv_004",
    product_id: "prod_oil_01",
    variant_name: "Groundnut Oil – 1L",
    regular_price: 220,
    discounted_price: 199,
    stock_quantity: 200,
    unit: "1 L",
    sku: "OIL-GROUND-1L",
    status: "active",
  },
  {
    id: "pv_005",
    product_id: "prod_oil_01",
    variant_name: "Groundnut Oil – 5L",
    regular_price: 1050,
    discounted_price: 999,
    stock_quantity: 10,
    unit: "5 L",
    sku: "OIL-GROUND-5L",
    status: "inactive",
  },
  {
    id: "pv_006",
    product_id: "prod_dal_01",
    variant_name: "Toor Dal – 1kg",
    regular_price: 180,
    discounted_price: 165,
    stock_quantity: 300,
    unit: "1 kg",
    sku: "DAL-TOOR-1KG",
    status: "active",
  },
];
export const cartItems = [
  {
    id: "ci_001",
    cart_id: "cart_1001",
    product_variant_id: "pv_001",
    quantity: 2,
  },
  {
    id: "ci_002",
    cart_id: "cart_1001",
    product_variant_id: "pv_002",
    quantity: 1,
  },
  {
    id: "ci_003",
    cart_id: "cart_1001",
    product_variant_id: "pv_003",
    quantity: 5,
  },
  {
    id: "ci_004",
    cart_id: "cart_1001",
    product_variant_id: "pv_004",
    quantity: 3,
  },
  {
    id: "ci_005",
    cart_id: "cart_1001",
    product_variant_id: "pv_005",
    quantity: 1,
  },
  {
    id: "ci_006",
    cart_id: "cart_1001",
    product_variant_id: "pv_006",
    quantity: 4,
  },
];
