// ecommerceData.js

export const dbData = {
  users: [
    {
      id: "u1",
      first_name: "Alice",
      last_name: "Johnson",
      email: "alice@example.com",
      phone: "555-0101",
      role: "customer",
      created_at: "2025-01-10",
      updated_at: "2025-01-10",
    },
    {
      id: "u2",
      first_name: "Bob",
      last_name: "Smith",
      email: "bob@example.com",
      phone: "555-0102",
      role: "customer",
      created_at: "2025-01-12",
      updated_at: "2025-01-12",
    },
    {
      id: "u3",
      first_name: "Charlie",
      last_name: "Brown",
      email: "charlie@gmail.com",
      phone: "555-0103",
      role: "customer",
      created_at: "2025-02-01",
      updated_at: "2025-02-01",
    },
    {
      id: "u4",
      first_name: "David",
      last_name: "Miller",
      email: "david@yahoo.com",
      phone: "555-0104",
      role: "customer",
      created_at: "2025-02-05",
      updated_at: "2025-02-05",
    },
    {
      id: "u5",
      first_name: "Eva",
      last_name: "Davis",
      email: "eva@outlook.com",
      phone: "555-0105",
      role: "customer",
      created_at: "2025-02-15",
      updated_at: "2025-02-15",
    },
    {
      id: "u6",
      first_name: "Admin",
      last_name: "Arul",
      email: "admin@aruldigitals.com",
      phone: "555-9999",
      role: "admin",
      created_at: "2025-01-01",
      updated_at: "2025-01-01",
    },
  ],

  addresses: [
    {
      id: "a1",
      user_id: "u1",
      full_name: "Alice Johnson",
      phone: "555-0101",
      address_line1: "123 Main St",
      city: "New York",
      state: "NY",
      pincode: "10001",
      country: "USA",
      is_default: true,
    },
    {
      id: "a2",
      user_id: "u1",
      full_name: "Alice Work",
      phone: "555-0101",
      address_line1: "456 Tech Park",
      city: "New York",
      state: "NY",
      pincode: "10010",
      country: "USA",
      is_default: false,
    },
    {
      id: "a3",
      user_id: "u2",
      full_name: "Bob Smith",
      phone: "555-0102",
      address_line1: "789 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      pincode: "90001",
      country: "USA",
      is_default: true,
    },
    {
      id: "a4",
      user_id: "u3",
      full_name: "Charlie Brown",
      phone: "555-0103",
      address_line1: "101 Pine St",
      city: "Chicago",
      state: "IL",
      pincode: "60601",
      country: "USA",
      is_default: true,
    },
    {
      id: "a5",
      user_id: "u4",
      full_name: "David Miller",
      phone: "555-0104",
      address_line1: "202 Maple Dr",
      city: "Austin",
      state: "TX",
      pincode: "73301",
      country: "USA",
      is_default: true,
    },
  ],

  categories: [
    {
      id: "c1",
      name: "Electronics",
      description: "Smartphones, Laptops, and Accessories",
      created_at: "2025-01-01",
    },
    {
      id: "c2",
      name: "Apparel",
      description: "Clothing, Shoes, and Hats",
      created_at: "2025-01-01",
    },
    {
      id: "c3",
      name: "Home & Garden",
      description: "Furniture and Kitchenware",
      created_at: "2025-01-01",
    },
    {
      id: "c4",
      name: "Books",
      description: "Fiction, Non-fiction, and Educational",
      created_at: "2025-01-01",
    },
    {
      id: "c5",
      name: "Sports",
      description: "Fitness gear and outdoor equipment",
      created_at: "2025-01-01",
    },
  ],

  categorie_images: [
    {
      id: "ci1",
      categories_id: "c1",
      image_path: "https://img.icons8.com/?size=80&id=59750&format=png",
      alt_text: "Electronics Category",
      is_primary: true,
    },
    {
      id: "ci2",
      categories_id: "c2",
      image_path: "https://img.icons8.com/?size=80&id=23330&format=png",
      alt_text: "Apparel Category",
      is_primary: true,
    },
  ],

  products: [
    {
      id: "pr1",
      name: "iPhone 15",
      description: "Latest Apple Smartphone",
      category_id: "c1",
      stock_quantity: 250,
      stock_unit: "gm",
      is_active: true,
      created_at: "2025-01-05",
    },
    {
      id: "pr2",
      name: "Cotton Crewneck T-Shirt",
      description: "100% Organic Cotton",
      category_id: "c2",
      stock_quantity: 50,
      stock_unit: "lt",
      is_active: true,
      created_at: "2025-01-06",
    },
    {
      id: "pr3",
      name: "Ergonomic Office Chair",
      description: "Premium lumbar support",
      category_id: "c3",
      stock_quantity: 150,
      stock_unit: "other",
      is_active: true,
      created_at: "2025-01-07",
    },
    {
      id: "pr4",
      name: "JavaScript: The Good Parts",
      description: "Classic programming book",
      category_id: "c4",
      stock_quantity: 430,
      stock_unit: "ml",
      is_active: true,
      created_at: "2025-01-08",
    },
    {
      id: "pr5",
      name: "Yoga Mat",
      description: "Non-slip 6mm mat",
      category_id: "c5",
      stock_quantity: 200,
      stock_unit: "kg",
      is_active: true,
      created_at: "2025-01-09",
    },
    {
      id: "pr6",
      name: "Sony WH-1000XM5",
      description: "Noise Cancelling Headphones",
      category_id: "c1",
      stock_quantity: 110,
      stock_unit: "gm",
      is_active: true,
      created_at: "2025-01-10",
    },
    {
      id: "pr7",
      name: "Running Shoes",
      description: "Lightweight breathable mesh",
      category_id: "c2",
      stock_quantity: 909,
      stock_unit: "gm",
      is_active: true,
      created_at: "2025-01-11",
    },
    {
      id: "pr8",
      name: "Non-Stick Frying Pan",
      description: "Diamond coated 12-inch",
      category_id: "c3",
      stock_quantity: 150,
      stock_unit: "lt",
      is_active: true,
      created_at: "2025-01-12",
    },
  ],

  product_images: [
    {
      id: "pimg1",
      product_id: "pr1",
      image_path: "https://img.icons8.com/?size=80&id=59750&format=png",
      alt_text: "iPhone 15 Blue",
      is_primary: false,
    },
    {
      id: "pimg2",
      product_id: "pr2",
      image_path: "https://img.icons8.com/?size=80&id=23330&format=png",
      alt_text: "White T-Shirt",
      is_primary: true,
    },
    {
      id: "pimg3",
      product_id: "pr6",
      image_path: "https://img.icons8.com/?size=80&id=59750&format=png",
      alt_text: "Sony Headphones",
      is_primary: false,
    },
  ],

  product_variants: [
    {
      id: "pv1",
      product_id: "pr1",
      variant_name: "128GB Blue",
      regular_price: 799.0,
      // discounted_price: 749.0,
      stock_quantity: 25,
      unit: "pcs",
      // sku: "IPH15-128-BLU",
    },
    {
      id: "pv2",
      product_id: "pr1",
      variant_name: "256GB Black",
      regular_price: 899.0,
      // discounted_price: 849.0,
      stock_quantity: 15,
      unit: "pcs",
      // sku: "IPH15-256-BLK",
    },
    {
      id: "pv3",
      product_id: "pr2",
      variant_name: "Large / White",
      regular_price: 25.0,
      // discounted_price: 20.0,
      stock_quantity: 100,
      unit: "pcs",
      // sku: "TSH-LRG-WHT",
    },
    {
      id: "pv4",
      product_id: "pr6",
      variant_name: "Silver",
      regular_price: 399.0,
      // discounted_price: 349.0,
      stock_quantity: 40,
      unit: "pcs",
      // sku: "SONY-XM5-SLV",
    },
    {
      id: "pv5",
      product_id: "pr3",
      variant_name: "Black Leather",
      regular_price: 299.0,
      // discounted_price: 299.0,
      stock_quantity: 10,
      unit: "pcs",
      // sku: "CHAIR-LTH-BLK",
    },
  ],

  carts: [
    { id: "ct1", user_id: "u1" },
    { id: "ct2", user_id: "u2" },
    { id: "ct3", user_id: "u3" },
    { id: "ct4", user_id: "u4" },
  ],

  cart_items: [
    { id: "ci1", cart_id: "ct1", product_variant_id: "pv1", quantity: 1 },
    { id: "ci2", cart_id: "ct1", product_variant_id: "pv3", quantity: 2 },
    { id: "ci3", cart_id: "ct2", product_variant_id: "pv4", quantity: 1 },
  ],

  orders: [
    {
      id: "o1",
      user_id: "u1",
      address_id: "a1",
      total_amount: 769.0,
      payment_status: "paid",
      order_status: "delivered",
      stripe_payment_id: "ch_3Mv1",
      created_at: "2025-02-10",
    },
    {
      id: "o2",
      user_id: "u2",
      address_id: "a3",
      total_amount: 349.0,
      payment_status: "paid",
      order_status: "shipped",
      stripe_payment_id: "ch_4Kx9",
      created_at: "2025-03-01",
    },
    {
      id: "o3",
      user_id: "u3",
      address_id: "a4",
      total_amount: 20.0,
      payment_status: "pending",
      order_status: "pending",
      stripe_payment_id: null,
      created_at: "2025-03-15",
    },
  ],

  order_items: [
    {
      id: "oi1",
      order_id: "o1",
      product_id: "pr1",
      product_variant_id: "pv1",
      quantity: 1,
      price: 749.0,
    },
    {
      id: "oi2",
      order_id: "o1",
      product_id: "pr2",
      product_variant_id: "pv3",
      quantity: 1,
      price: 20.0,
    },
    {
      id: "oi3",
      order_id: "o2",
      product_id: "pr6",
      product_variant_id: "pv4",
      quantity: 1,
      price: 349.0,
    },
  ],

  promotions: [
    {
      id: "p1",
      name: "New Year Electronics",
      promotion_type: "PRODUCT",
      discount_type: "PERCENTAGE",
      discount_value: 10.0,
      is_active: true,
      start_date: "2025-01-01",
      end_date: "2025-01-31",
    },
    {
      id: "p2",
      name: "Fashion Clearout",
      promotion_type: "CATEGORY",
      discount_type: "FLAT",
      discount_value: 5.0,
      is_active: true,
      start_date: "2025-02-01",
      end_date: "2025-03-31",
    },
  ],

  promotion_products: [
    { id: "pp1", promotion_id: "p1", product_id: "pr1" },
    { id: "pp2", promotion_id: "p1", product_id: "pr6" },
  ],

  promotion_categories: [{ id: "pc1", promotion_id: "p2", category_id: "c2" }],

  promo_codes: [
    {
      id: "pcde1",
      code: "SAVE50",
      discount_type: "FLAT",
      discount_value: 50.0,
      min_order_value: 500.0,
      is_active: true,
    },
    {
      id: "pcde2",
      code: "WELCOME10",
      discount_type: "PERCENTAGE",
      discount_value: 10.0,
      min_order_value: 0.0,
      is_active: true,
    },
  ],

  promo_code_users: [
    {
      id: "pcu1",
      promo_code_id: "pcde1",
      user_id: "u1",
      used_at: "2025-02-10",
    },
  ],

  order_discounts: [
    {
      id: "od1",
      order_id: "o1",
      discount_source: "PROMO_CODE",
      source_id: "pcde1",
      discount_amount: 50.0,
    },
  ],

  notifications: [
    {
      id: "n1",
      user_id: "u1",
      type: "email",
      content: "Your order o1 has been delivered!",
      status: "sent",
      created_at: "2025-02-10",
    },
    {
      id: "n2",
      user_id: "u2",
      type: "whatsapp",
      content: "Order o2 is on its way!",
      status: "sent",
      created_at: "2025-03-01",
    },
  ],
};
