const promotionsData = [
  {
    id: 1,
    name: "Rice Festival Offer",
    promotion_type: "CATEGORY",
    discount_type: "PERCENTAGE",
    discount_value: 10,
    minimum_order_value: 0,
    start_date: "2025-01-01",
    end_date: "2025-01-10",
    is_active: true,
    product_ids: [],
    category_ids: [1, 2],
  },
  {
    id: 2,
    name: "Basmati Special",
    promotion_type: "PRODUCT",
    discount_type: "PERCENTAGE",
    discount_value: 20,
    minimum_order_value: 100,
    start_date: "2025-01-05",
    end_date: "2025-01-20",
    is_active: true,
    product_ids: [2, 5],
    category_ids: [],
  },
  {
    id: 3,
    name: "Cart ₹200 OFF",
    promotion_type: "CART",
    discount_type: "FLAT",
    discount_value: 200,
    minimum_order_value: 0,
    start_date: "2025-01-01",
    end_date: "2025-01-31",
    is_active: false,
    product_ids: [],
    category_ids: [],
  },
  {
    id: 4,
    name: "Free Shipping Above ₹999",
    promotion_type: "SHIPPING",
    discount_type: "FLAT",
    discount_value: 80,
    minimum_order_value: 200,
    start_date: "2025-01-01",
    end_date: "2025-01-31",
    is_active: true,
    product_ids: [],
    category_ids: [],
  },
  {
    id: 5,
    name: "Vegetable Bonanza",
    promotion_type: "PRODUCT",
    discount_type: "PERCENTAGE",
    discount_value: 15,
    minimum_order_value: 100,
    start_date: "2025-02-01",
    end_date: "2025-02-10",
    is_active: true,
    product_ids: [1, 3, 7],
    category_ids: [],
  },
  {
    id: 6,
    name: "Sweet Treats Sale",
    promotion_type: "CATEGORY",
    discount_type: "FLAT",
    discount_value: 50,
    minimum_order_value: 500,
    start_date: "2025-03-01",
    end_date: "2025-03-15",
    is_active: true,
    product_ids: [],
    category_ids: [2],
  },
];

export default promotionsData;
